version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: inmet_weather_raw
        description: "Tabela bruta carregada a partir dos CSVs históricos do INMET."

models:
  - name: stg_inmet_weather
    description: "Camada silver com padronização de tipos e nomes de colunas do INMET."
    columns:
      - name: data_referencia
        tests:
          - not_null
      - name: codigo_wmo
        tests:
          - not_null
      - name: radiacao_global_kj_m2
        description: "Radiação global horária (kJ/m²)."
      - name: vento_direcao_gr
        description: "Direção horária do vento em graus."
      - name: vento_rajada_max_m_s
        description: "Rajada máxima do vento na hora (m/s)."
      - name: vento_velocidade_m_s
        description: "Velocidade horária do vento (m/s)."

  - name: dim_station
    description: "Dimensão de estações meteorológicas (WMO)."
    columns:
      - name: station_sk
        tests:
          - unique
          - not_null
      - name: codigo_wmo
        tests:
          - not_null

  - name: dim_date
    description: "Dimensão de calendário para análises temporais."
    columns:
      - name: date_sk
        tests:
          - unique
          - not_null
      - name: mes
        tests:
          - accepted_values:
              values: [1,2,3,4,5,6,7,8,9,10,11,12]

  - name: fact_weather_hourly
    description: "Fato horário de observações meteorológicas por estação."
    columns:
      - name: weather_event_sk
        tests:
          - unique
          - not_null
      - name: station_sk
        tests:
          - not_null
      - name: date_sk
        tests:
          - not_null
      - name: intensidade_chuva
        tests:
          - accepted_values:
              values: ['sem_dado', 'sem_chuva', 'chuva_fraca', 'chuva_moderada', 'chuva_intensa']
      - name: periodo_dia
        tests:
          - accepted_values:
              values: ['madrugada', 'manha', 'tarde', 'noite']
      - name: faixa_radiacao
        tests:
          - accepted_values:
              values: ['sem_dado', 'sem_radiacao', 'radiacao_baixa', 'radiacao_media', 'radiacao_alta']
      - name: direcao_vento_cardinal
        tests:
          - accepted_values:
              values: ['sem_dado', 'N', 'NE', 'E', 'SE', 'S', 'SO', 'O', 'NO']
      - name: intensidade_vento
        tests:
          - accepted_values:
              values: ['sem_dado', 'calmo', 'fraco', 'moderado', 'forte']
