CREATE SCHEMA IF NOT EXISTS raw;
CREATE SCHEMA IF NOT EXISTS silver;
CREATE SCHEMA IF NOT EXISTS gold;

CREATE TABLE IF NOT EXISTS raw.ingestion_log (
  ingestion_id BIGSERIAL PRIMARY KEY,
  loaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  load_mode VARCHAR(30) NOT NULL,
  source_year INTEGER NOT NULL,
  source_file TEXT NOT NULL,
  rows_loaded INTEGER NOT NULL,
  status VARCHAR(30) NOT NULL,
  details TEXT
);
