-- Cria a arquitetura medalhão (raw → silver → gold) no inmet_db e a tabela de log de ingestão

CREATE SCHEMA IF NOT EXISTS raw;
CREATE SCHEMA IF NOT EXISTS silver;
CREATE SCHEMA IF NOT EXISTS gold;

-- Garante que analytics_user enxerga os schemas
GRANT USAGE, CREATE ON SCHEMA raw TO analytics_user;
GRANT USAGE, CREATE ON SCHEMA silver TO analytics_user;
GRANT USAGE, CREATE ON SCHEMA gold TO analytics_user;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA raw TO analytics_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA silver TO analytics_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA gold TO analytics_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA raw GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO analytics_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA silver GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO analytics_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA gold GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO analytics_user;

GRANT USAGE ON ALL SEQUENCES IN SCHEMA raw TO analytics_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA raw GRANT USAGE ON SEQUENCES TO analytics_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA silver GRANT USAGE ON SEQUENCES TO analytics_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA gold GRANT USAGE ON SEQUENCES TO analytics_user;

CREATE TABLE IF NOT EXISTS raw.ingestion_log (
  ingestion_id BIGSERIAL PRIMARY KEY
  ,loaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  ,load_mode VARCHAR(30) NOT NULL
  ,source_year INTEGER NOT NULL
  ,source_file TEXT NOT NULL
  ,rows_loaded INTEGER NOT NULL
  ,status VARCHAR(30) NOT NULL
  ,details TEXT
);