name: 'inmet_analytics'
version: '1.0.0'
config-version: 2

profile: 'inmet_analytics'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
target-path: "/tmp/dbt_target"
packages-install-path: "/tmp/dbt_packages"

clean-targets:
  - "/tmp/dbt_target"
  - "/tmp/dbt_packages"

models:
  inmet_analytics:
    +materialized: view
    staging:
      +schema: silver
      +materialized: view
    marts:
      +schema: gold
      +materialized: table
