{% macro uf_to_timezone(uf_col) %}
  CASE {{ uf_col }}
    WHEN 'AC' THEN 'America/Rio_Branco'
    WHEN 'AL' THEN 'America/Maceio'
    WHEN 'AP' THEN 'America/Belem'
    WHEN 'BA' THEN 'America/Bahia'
    WHEN 'CE' THEN 'America/Fortaleza'
    WHEN 'DF' THEN 'America/Sao_Paulo'
    WHEN 'ES' THEN 'America/Sao_Paulo'
    WHEN 'GO' THEN 'America/Sao_Paulo'
    WHEN 'MA' THEN 'America/Fortaleza'
    WHEN 'MG' THEN 'America/Sao_Paulo'
    WHEN 'PA' THEN 'America/Belem'
    WHEN 'PB' THEN 'America/Fortaleza'
    WHEN 'PE' THEN 'America/Recife'
    WHEN 'PI' THEN 'America/Fortaleza'
    WHEN 'PR' THEN 'America/Sao_Paulo'
    WHEN 'RJ' THEN 'America/Sao_Paulo'
    WHEN 'RN' THEN 'America/Fortaleza'
    WHEN 'RO' THEN 'America/Porto_Velho'
    WHEN 'RR' THEN 'America/Boa_Vista'
    WHEN 'RS' THEN 'America/Sao_Paulo'
    WHEN 'SC' THEN 'America/Sao_Paulo'
    WHEN 'SE' THEN 'America/Maceio'
    WHEN 'SP' THEN 'America/Sao_Paulo'
    WHEN 'TO' THEN 'America/Araguaina'
    WHEN 'MS' THEN 'America/Campo_Grande'
    WHEN 'MT' THEN 'America/Cuiaba'
    WHEN 'AM' THEN 'America/Manaus'
    ELSE 'America/Sao_Paulo'
    END
{% endmacro %}