{% macro uf_to_timezone(uf_col) %}
  case {{ uf_col }}
    when 'AC' then 'America/Rio_Branco'
    when 'AL' then 'America/Maceio'
    when 'AP' then 'America/Belem'
    when 'BA' then 'America/Bahia'
    when 'CE' then 'America/Fortaleza'
    when 'DF' then 'America/Sao_Paulo'
    when 'ES' then 'America/Sao_Paulo'
    when 'GO' then 'America/Sao_Paulo'
    when 'MA' then 'America/Fortaleza'
    when 'MG' then 'America/Sao_Paulo'
    when 'PA' then 'America/Belem'
    when 'PB' then 'America/Fortaleza'
    when 'PE' then 'America/Recife'
    when 'PI' then 'America/Fortaleza'
    when 'PR' then 'America/Sao_Paulo'
    when 'RJ' then 'America/Sao_Paulo'
    when 'RN' then 'America/Fortaleza'
    when 'RO' then 'America/Porto_Velho'
    when 'RR' then 'America/Boa_Vista'
    when 'RS' then 'America/Sao_Paulo'
    when 'SC' then 'America/Sao_Paulo'
    when 'SE' then 'America/Maceio'
    when 'SP' then 'America/Sao_Paulo'
    when 'TO' then 'America/Araguaina'
    when 'MS' then 'America/Campo_Grande'
    when 'MT' then 'America/Cuiaba'
    when 'AM' then 'America/Manaus'
    else 'America/Sao_Paulo'
  end
{% endmacro %}